language: node_js
node_js:
- "stable"
services:
  - postgresql
cache:
  directories:
    - "node_modules"
before_install: cd ./Backend
install:
  - npm install
before_script:
  - psql -c 'create database testdb;' -U postgres
script:
  - npm run test
after_success:
- npm run coveralls